name: GraalVM Native build
on: 
  push: 
    branches: "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: |
          mvn deploy -Dpackaging=jar -s settings.xml -Dgithub.token=${{ secrets.GITHUB_TOKEN }}
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-SNAPSHOT
          mvn deploy -Dpackaging=jar -s settings.xml -Dgithub.token=${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
         name: discord-notifier
         path: target/*iscord*
